name = "Reap N' Sow"
author = "ChefMooon"
version = "1.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "48851d1c23bd8905d1496c89a7e62580cf811e1dc720125b72786212a6fc28d5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
