name = "Reap N' Sow"
author = "ChefMooon"
version = "1.4.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "edd64b3606971824ab8e7154ed7d6b3168fd569fafba77a34e3ca311b4e4f3b6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
